### ISSUE TITLE
sketch package no longer working in Google collab

### ISSUE THREAD

**Issue by nvamsimohan** [approximatelabs/sketch#35]
Hello! I recently installed Sketch and imported a dataset with 18 columns. Previously, I could use the 'how to' functions on this dataset, but now they're not generating the code as they used to. Any update is greatly appreciated, thanks!

**Comment by nvamsimohan** [comment]
Btw, I'm using Google colab for Python!

**Comment by nvamsimohan** [comment]
![sketch package colab error](https://github.com/approximatelabs/sketch/assets/4365176/066c2909-449b-48d1-97ac-d9e0230179fa)
Attaching a screen shot

**Comment by sooeun67** [comment]
Having the same issue!

<img width="1696" alt="스크린샷 2024-01-16 오전 11 12 45" src="https://github.com/approximatelabs/sketch/assets/32501921/dbf24894-c308-4710-8dee-b72367be2ac5">

**Comment by fbeneventi** [comment]
Probably due to the model (text-davinci-003) deprecation from OpenAI  https://platform.openai.com/docs/deprecations/2023-07-06-gpt-and-embeddings

**Comment by bluecoconut** [comment]
Yup! This was caused by the model deprecation.

Just pushed a new version `0.5.0`, run `pip install -U sketch` and it will fix it!
