### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by pdavis01** [approximatelabs/sketch#8]
Hello, Tried to use sketch with a simple use case, but I'm not getting results.  I'm working in Spyder IDE on Anaconda, pip install of sketch worked fine, but my console output is always: "<IPython.core.display.HTML object>"

This happens regardless of the type of question I ask it, following the documentation.

Thank you

**Comment by bluecoconut** [comment]
As @hugetim hugetim says, this is the IDE not rendering HTML output
https://stackoverflow.com/questions/47075946/replicate-jupyter-html-output-using-ipython-and-spyder-instead

Specifically, sketch has a flag you can add, `df.sketh.ask(..., call_display=False)` and this should work for you @pdavis01
