### ISSUE TITLE
Discord link not working

### ISSUE THREAD

**Issue by hugetim** [approximatelabs/sketch#9]
I'm seeing "Invalid Invite" when I click it.

**Comment by bluecoconut** [comment]
I just tried it again and it seemed to work for me, also double checking in discord shows it as no expiration.

Here's the URL directly
https://discord.gg/kW9nBQErGe

Can you try again? Looking forward to more to join the conversation on discord!

**Comment by hugetim** [comment]
Yep, the problem was on my end, to do with email verification or another security check. Now that I've cleared those up in my Discord account, the link works for me.
